### ISSUE TITLE
how to I infer "rules[0] --> rules[1], confidence = rules[2]" from the rules

### ISSUE THREAD

**Issue by amansingh9097** [chonyy/apriori_python#1]
First of all, thank you so much for this. This is comparatively computationally faster than the other implementations of Apirori I found on GitHub.

In the README, you have mentioned this sort of pattern<br>
`rules[0] --> rules[1], confidence = rules[2]`

How do I infer this from the rules set?

Following are the first 3 rules generated from my run of apriori_python on a toy dataset:
`[{'Apple'}, {'Orange'}, 0.5008052439747973] #rules[0]`
`[{'Grapes', 'Orange'}, {'Apple', 'Banana'}, 0.5056131260794473] #rules[1]`
`[{'Banana', 'Kiwi'}, {'Apple'}, 0.5072046109510087] #rules[2]`

Also, what exactly is meant by `rules[0] --> rules[1], confidence = rules[2]` ?
Does it mean that when `rules[0]` is the antecedent then `rules[1]` is the consequent with a confidence mentioned against `rules[1]` that together forms the `rules[2]`?

Sorry for so many dumb questions, I'm still new to ARM modelling.

**Comment by chonyy** [comment]
Hi @amansingh9097 ,

Thanks for the question.

I apologize for the misleading comment in the README.
Your confusion totally makes sense.

To explain it clearly, it's actually
``` Python
for rule in rules:
  # rule[0] --> rule[1], confidence = rule[2]
```
Take your first rule for example
`[{'Apple'}, {'Orange'}, 0.5008052439747973] #rules[0]`
The association rule is
`Apple --> Orange` 
and the confidence of this rule is 0.5008052439747973

Hope this could help you understand it better.

Thanks,
Chonyy

**Comment by amansingh9097** [comment]
thanks Chonyy :)
